part of '../lite_forms_configuration.dart';

LiteFormsConfiguration _thinFields(
  BuildContext context,
) {
  final primaryColor = Theme.of(context).primaryColor;
  const cornerRadius = 6.0;
  const normalBorderWidth = .1;
  const focusedBorderWidth = .4;
  const borderRadius = BorderRadius.only(
    topLeft: Radius.circular(
      cornerRadius,
    ),
    topRight: Radius.circular(
      cornerRadius,
    ),
    bottomRight: Radius.circular(
      cornerRadius,
    ),
    bottomLeft: Radius.circular(
      cornerRadius,
    ),
  );
  const defaultBorder = OutlineInputBorder(
    borderRadius: borderRadius,
  );
  const sidePadding = 12.0;
  return LiteFormsConfiguration(
    defaultDateFormat: 'dd MMM, yyyy',
    defaultTimeFormat: 'HH:mm',
    dropSelectorSettings: const DropSelectorSettings(
      dropSelectorActionType: LiteDropSelectorActionType.simple,
      dropSelectorType: LiteDropSelectorViewType.adaptive,
    ),
    autovalidateMode: AutovalidateMode.onUserInteraction,
    useAutogeneratedHints: true,
    allowUnfocusOnTapOutside: true,
    defaultTextEntryModalRouteSettings: TextEntryModalRouteSettings(
      backgroundOpacity: .95,
    ),
    lightTheme: LiteFormsTheme(
      defaultTextStyle: const TextStyle(
        fontSize: 15.0,
        color: Color.fromARGB(255, 32, 32, 32),
      ),
      destructiveColor: Colors.red,
      filePickerDecoration: const BoxDecoration(
        borderRadius: borderRadius,
        border: Border.fromBorderSide(
          BorderSide(
            width: normalBorderWidth,
          ),
        ),
      ),
      inputDecoration: InputDecoration(
        contentPadding: const EdgeInsets.only(
          left: sidePadding,
          right: sidePadding,
        ),
        filled: false,
        errorStyle: const TextStyle(
          fontSize: 16.0,
          color: Colors.red,
        ),
        border: defaultBorder,
        enabledBorder: defaultBorder.copyWith(
          borderSide: const BorderSide(
            width: normalBorderWidth,
          ),
        ),
        focusedBorder: defaultBorder.copyWith(
          borderSide: BorderSide(
            width: focusedBorderWidth,
            color: primaryColor,
          ),
        ),
      ),
    ),
    darkTheme: LiteFormsTheme(
      defaultTextStyle: const TextStyle(
        fontSize: 15.0,
        color: Color.fromARGB(255, 248, 248, 248),
      ),
      destructiveColor: Colors.redAccent,
      inputDecoration: InputDecoration(
        contentPadding: const EdgeInsets.only(
          left: sidePadding,
          right: sidePadding,
        ),
        filled: false,
        errorStyle: const TextStyle(
          fontSize: 16.0,
          color: Colors.redAccent,
        ),
        border: defaultBorder,
        enabledBorder: defaultBorder.copyWith(
          borderSide: const BorderSide(
            width: normalBorderWidth,
            color: Colors.white,
          ),
        ),
        focusedBorder: defaultBorder.copyWith(
          borderSide: const BorderSide(
            width: focusedBorderWidth,
            color: Colors.white,
          ),
        ),
      ),
      filePickerDecoration: const BoxDecoration(
        borderRadius: borderRadius,
        border: Border.fromBorderSide(
          BorderSide(
            width: normalBorderWidth,
            color: Colors.white,
          ),
        ),
      ),
    ),
  );
}
