part of '../lite_forms_configuration.dart';

LiteFormsConfiguration _vanila(BuildContext context) {
  final primaryColor = Theme.of(context).primaryColor;
  const cornerRadius = 6.0;
  const normalBorderWidth = .1;
  const focusedBorderWidth = .4;
  const borderRadius = BorderRadius.only(
    topLeft: Radius.circular(
      cornerRadius,
    ),
    topRight: Radius.circular(
      cornerRadius,
    ),
    bottomRight: Radius.circular(
      cornerRadius,
    ),
    bottomLeft: Radius.circular(
      cornerRadius,
    ),
  );
  const defaultBorder = OutlineInputBorder(
    borderRadius: borderRadius,
  );

  /// Must be called in the beginning.
  /// Basically that's all you need
  /// to start using Lite Forms
  // initializeLiteForms(
  /// optional configuration which will be used as default
  return LiteFormsConfiguration(
    defaultDateFormat: 'dd MMM, yyyy',
    defaultTimeFormat: 'HH:mm',
    dropSelectorSettings: const LiteDropSelectorSettings(),
    autovalidateMode: AutovalidateMode.onUserInteraction,
    useAutogeneratedHints: true,
    allowUnfocusOnTapOutside: true,
    defaultTextEntryModalRouteSettings: TextEntryModalRouteSettings(
      backgroundOpacity: .95,
    ),
    lightTheme: LiteFormsTheme(
      destructiveColor: Colors.red,
      filePickerDecoration: const BoxDecoration(
        borderRadius: borderRadius,
        border: Border.fromBorderSide(
          BorderSide(
            width: normalBorderWidth,
          ),
        ),
      ),
      inputDecoration: InputDecoration(
        filled: false,
        errorStyle: const TextStyle(
          fontSize: 16.0,
          color: Colors.red,
        ),
        border: defaultBorder,
        enabledBorder: defaultBorder.copyWith(
          borderSide: const BorderSide(
            width: normalBorderWidth,
          ),
        ),
        focusedBorder: defaultBorder.copyWith(
          borderSide: BorderSide(
            width: focusedBorderWidth,
            color: primaryColor,
          ),
        ),
      ),
    ),
    darkTheme: LiteFormsTheme(
      destructiveColor: Colors.redAccent,
      inputDecoration: InputDecoration(
        filled: false,
        errorStyle: const TextStyle(
          fontSize: 16.0,
          color: Colors.redAccent,
        ),
        border: defaultBorder,
        enabledBorder: defaultBorder.copyWith(
          borderSide: const BorderSide(
            width: normalBorderWidth,
            color: Colors.white,
          ),
        ),
        focusedBorder: defaultBorder.copyWith(
          borderSide: const BorderSide(
            width: focusedBorderWidth,
            color: Colors.white,
          ),
        ),
      ),
      filePickerDecoration: const BoxDecoration(
        borderRadius: borderRadius,
        border: Border.fromBorderSide(
          BorderSide(
            width: normalBorderWidth,
            color: Colors.white,
          ),
        ),
      ),
    ),
  );
}
