part of 'lite_country_selector.dart';

class CountryData with SearchQueryMixin {
  final String name;
  final String simplifiedName;
  final String isoCode;
  final String threeLetterCode;

  String get countryId {
    return isoCode;
  }

  int sortOrder = 0;

  CountryData({
    required this.name,
    required this.simplifiedName,
    required this.isoCode,
    required this.threeLetterCode,
  }) {
    prepareSearch([
      simplifiedName,
      isoCode,
      threeLetterCode,
    ]);
  }

  @override
  bool operator ==(covariant CountryData other) {
    return other.isoCode == isoCode;
  }

  @override
  int get hashCode {
    return isoCode.hashCode;
  }

  String get lowerIsoCode {
    return isoCode.toLowerCase();
  }
}

/// Tries to search a country by a name, iso code or a three letter code
List<CountryData?> tryFindCountries(String value) {
  return allCountries.where((e) => e.isMatchingSearch(value)).toList();
}

final List<CountryData> allCountries = [
  CountryData(
    name: "Austria",
    simplifiedName: "austria",
    isoCode: "AT",
    threeLetterCode: "AUT",
  ),
  CountryData(
    name: "Belgium",
    simplifiedName: "belgium",
    isoCode: "BE",
    threeLetterCode: "BEL",
  ),
  CountryData(
    name: "Canada",
    simplifiedName: "canada",
    isoCode: "CA",
    threeLetterCode: "CAN",
  ),
  CountryData(
    name: "Czech Republic",
    simplifiedName: "czech republic",
    isoCode: "CZ",
    threeLetterCode: "CZE",
  ),
  CountryData(
    name: "Denmark",
    simplifiedName: "denmark",
    isoCode: "DK",
    threeLetterCode: "DNK",
  ),
  CountryData(
    name: "Finland",
    simplifiedName: "finland",
    isoCode: "FI",
    threeLetterCode: "FIN",
  ),
  CountryData(
    name: "France",
    simplifiedName: "france",
    isoCode: "FR",
    threeLetterCode: "FRA",
  ),
  CountryData(
    name: "Germany",
    simplifiedName: "germany",
    isoCode: "DE",
    threeLetterCode: "DEU",
  ),
  CountryData(
    name: "Greece",
    simplifiedName: "greece",
    isoCode: "GR",
    threeLetterCode: "GRC",
  ),
  CountryData(
    name: "Iceland",
    simplifiedName: "iceland",
    isoCode: "IS",
    threeLetterCode: "ISL",
  ),
  CountryData(
    name: "Ireland",
    simplifiedName: "ireland",
    isoCode: "IE",
    threeLetterCode: "IRL",
  ),
  CountryData(
    name: "Italy",
    simplifiedName: "italy",
    isoCode: "IT",
    threeLetterCode: "ITA",
  ),
  CountryData(
    name: "Latvia",
    simplifiedName: "latvia",
    isoCode: "LV",
    threeLetterCode: "LVA",
  ),
  CountryData(
    name: "Luxembourg",
    simplifiedName: "luxembourg",
    isoCode: "LU",
    threeLetterCode: "LUX",
  ),
  CountryData(
    name: "Malta",
    simplifiedName: "malta",
    isoCode: "MT",
    threeLetterCode: "MLT",
  ),
  CountryData(
    name: "Netherlands",
    simplifiedName: "netherlands",
    isoCode: "NL",
    threeLetterCode: "NLD",
  ),
  CountryData(
    name: "Norway",
    simplifiedName: "norway",
    isoCode: "NO",
    threeLetterCode: "NOR",
  ),
  CountryData(
    name: "Poland",
    simplifiedName: "poland",
    isoCode: "PL",
    threeLetterCode: "POL",
  ),
  CountryData(
    name: "Portugal",
    simplifiedName: "portugal",
    isoCode: "PT",
    threeLetterCode: "PRT",
  ),
  CountryData(
    name: "Romania",
    simplifiedName: "romania",
    isoCode: "RO",
    threeLetterCode: "ROU",
  ),
  CountryData(
    name: "Slovakia",
    simplifiedName: "slovakia",
    isoCode: "SK",
    threeLetterCode: "SVK",
  ),
  CountryData(
    name: "Spain",
    simplifiedName: "spain",
    isoCode: "ES",
    threeLetterCode: "ESP",
  ),
  CountryData(
    name: "Sweden",
    simplifiedName: "sweden",
    isoCode: "SE",
    threeLetterCode: "SWE",
  ),
  CountryData(
    name: "Switzerland",
    simplifiedName: "switzerland",
    isoCode: "CH",
    threeLetterCode: "CHE",
  ),
  CountryData(
    name: "United Kingdom",
    simplifiedName: "united kingdom of great britain and northern ireland",
    isoCode: "GB",
    threeLetterCode: "GBR",
  ),
  CountryData(
    name: "United States of America",
    simplifiedName: "united states of america",
    isoCode: "US",
    threeLetterCode: "USA",
  ),
  CountryData(
    name: "Viet Nam",
    simplifiedName: "viet nam",
    isoCode: "VN",
    threeLetterCode: "VNM",
  ),
  CountryData(
    name: "Afghanistan",
    simplifiedName: "afghanistan",
    isoCode: "AF",
    threeLetterCode: "AFG",
  ),
  CountryData(
    name: "Aland Islands",
    simplifiedName: "aland islands",
    isoCode: "AX",
    threeLetterCode: "ALA",
  ),
  CountryData(
    name: "Albania",
    simplifiedName: "albania",
    isoCode: "AL",
    threeLetterCode: "ALB",
  ),
  CountryData(
    name: "Algeria",
    simplifiedName: "algeria",
    isoCode: "DZ",
    threeLetterCode: "DZA",
  ),
  CountryData(
    name: "American Samoa",
    simplifiedName: "american samoa",
    isoCode: "AS",
    threeLetterCode: "ASM",
  ),
  CountryData(
    name: "Andorra",
    simplifiedName: "andorra",
    isoCode: "AD",
    threeLetterCode: "AND",
  ),
  CountryData(
    name: "Angola",
    simplifiedName: "angola",
    isoCode: "AO",
    threeLetterCode: "AGO",
  ),
  CountryData(
    name: "Anguilla",
    simplifiedName: "anguilla",
    isoCode: "AI",
    threeLetterCode: "AIA",
  ),
  // CountryData(
  //   name: "Antarctica",
  //   simplifiedName: "antarctica",
  //   isoCode: "AQ",
  //   threeLetterCode: "ATA",
  // ),
  CountryData(
    name: "Antigua and Barbuda",
    simplifiedName: "antigua and barbuda",
    isoCode: "AG",
    threeLetterCode: "ATG",
  ),
  CountryData(
    name: "Argentina",
    simplifiedName: "argentina",
    isoCode: "AR",
    threeLetterCode: "ARG",
  ),
  CountryData(
    name: "Armenia",
    simplifiedName: "armenia",
    isoCode: "AM",
    threeLetterCode: "ARM",
  ),
  CountryData(
    name: "Aruba",
    simplifiedName: "aruba",
    isoCode: "AW",
    threeLetterCode: "ABW",
  ),
  CountryData(
    name: "Australia",
    simplifiedName: "australia",
    isoCode: "AU",
    threeLetterCode: "AUS",
  ),
  CountryData(
    name: "Azerbaijan",
    simplifiedName: "azerbaijan",
    isoCode: "AZ",
    threeLetterCode: "AZE",
  ),
  CountryData(
    name: "Bahamas",
    simplifiedName: "bahamas",
    isoCode: "BS",
    threeLetterCode: "BHS",
  ),
  CountryData(
    name: "Bahrain",
    simplifiedName: "bahrain",
    isoCode: "BH",
    threeLetterCode: "BHR",
  ),
  CountryData(
    name: "Bangladesh",
    simplifiedName: "bangladesh",
    isoCode: "BD",
    threeLetterCode: "BGD",
  ),
  CountryData(
    name: "Barbados",
    simplifiedName: "barbados",
    isoCode: "BB",
    threeLetterCode: "BRB",
  ),
  CountryData(
    name: "Belarus",
    simplifiedName: "belarus",
    isoCode: "BY",
    threeLetterCode: "BLR",
  ),
  CountryData(
    name: "Belize",
    simplifiedName: "belize",
    isoCode: "BZ",
    threeLetterCode: "BLZ",
  ),
  CountryData(
    name: "Benin",
    simplifiedName: "benin",
    isoCode: "BJ",
    threeLetterCode: "BEN",
  ),
  CountryData(
    name: "Bermuda",
    simplifiedName: "bermuda",
    isoCode: "BM",
    threeLetterCode: "BMU",
  ),
  CountryData(
    name: "Bhutan",
    simplifiedName: "bhutan",
    isoCode: "BT",
    threeLetterCode: "BTN",
  ),
  CountryData(
    name: "Bolivia",
    simplifiedName: "bolivia",
    isoCode: "BO",
    threeLetterCode: "BOL",
  ),
  CountryData(
    name: "Bosnia and Herzegovina",
    simplifiedName: "bosnia and herzegovina",
    isoCode: "BA",
    threeLetterCode: "BIH",
  ),
  CountryData(
    name: "Botswana",
    simplifiedName: "botswana",
    isoCode: "BW",
    threeLetterCode: "BWA",
  ),
  CountryData(
    name: "Bouvet Island",
    simplifiedName: "bouvet island",
    isoCode: "BV",
    threeLetterCode: "BVT",
  ),
  CountryData(
    name: "Brazil",
    simplifiedName: "brazil",
    isoCode: "BR",
    threeLetterCode: "BRA",
  ),
  CountryData(
    name: "British Virgin Islands",
    simplifiedName: "british virgin islands",
    isoCode: "VG",
    threeLetterCode: "VGB",
  ),
  CountryData(
    name: "British Indian Ocean Territory",
    simplifiedName: "british indian ocean territory",
    isoCode: "IO",
    threeLetterCode: "IOT",
  ),
  CountryData(
    name: "Brunei Darussalam",
    simplifiedName: "brunei darussalam",
    isoCode: "BN",
    threeLetterCode: "BRN",
  ),
  CountryData(
    name: "Bulgaria",
    simplifiedName: "bulgaria",
    isoCode: "BG",
    threeLetterCode: "BGR",
  ),
  CountryData(
    name: "Burkina Faso",
    simplifiedName: "burkina faso",
    isoCode: "BF",
    threeLetterCode: "BFA",
  ),
  CountryData(
    name: "Burundi",
    simplifiedName: "burundi",
    isoCode: "BI",
    threeLetterCode: "BDI",
  ),
  CountryData(
    name: "Cambodia",
    simplifiedName: "cambodia",
    isoCode: "KH",
    threeLetterCode: "KHM",
  ),
  CountryData(
    name: "Cameroon",
    simplifiedName: "cameroon",
    isoCode: "CM",
    threeLetterCode: "CMR",
  ),
  CountryData(
    name: "Cape Verde",
    simplifiedName: "cape verde",
    isoCode: "CV",
    threeLetterCode: "CPV",
  ),
  CountryData(
    name: "Cayman Islands",
    simplifiedName: "cayman islands",
    isoCode: "KY",
    threeLetterCode: "CYM",
  ),
  CountryData(
    name: "Central African Republic",
    simplifiedName: "central african republic",
    isoCode: "CF",
    threeLetterCode: "CAF",
  ),
  CountryData(
    name: "Chad",
    simplifiedName: "chad",
    isoCode: "TD",
    threeLetterCode: "TCD",
  ),
  CountryData(
    name: "Chile",
    simplifiedName: "chile",
    isoCode: "CL",
    threeLetterCode: "CHL",
  ),
  CountryData(
    name: "China",
    simplifiedName: "china",
    isoCode: "CN",
    threeLetterCode: "CHN",
  ),
  CountryData(
    name: "Hong Kong, SAR China",
    simplifiedName: "hong kong, sar china",
    isoCode: "HK",
    threeLetterCode: "HKG",
  ),
  CountryData(
    name: "Macao, SAR China",
    simplifiedName: "macao, sar china",
    isoCode: "MO",
    threeLetterCode: "MAC",
  ),
  CountryData(
    name: "Christmas Island",
    simplifiedName: "christmas island",
    isoCode: "CX",
    threeLetterCode: "CXR",
  ),
  CountryData(
    name: "Cocos (Keeling) Islands",
    simplifiedName: "cocos (keeling) islands",
    isoCode: "CC",
    threeLetterCode: "CCK",
  ),
  CountryData(
    name: "Colombia",
    simplifiedName: "colombia",
    isoCode: "CO",
    threeLetterCode: "COL",
  ),
  CountryData(
    name: "Comoros",
    simplifiedName: "comoros",
    isoCode: "KM",
    threeLetterCode: "COM",
  ),
  CountryData(
    name: "Congo (Brazzaville)",
    simplifiedName: "congo (brazzaville)",
    isoCode: "CG",
    threeLetterCode: "COG",
  ),
  CountryData(
    name: "Congo, (Kinshasa)",
    simplifiedName: "congo, (kinshasa)",
    isoCode: "CD",
    threeLetterCode: "COD",
  ),
  CountryData(
    name: "Cook Islands",
    simplifiedName: "cook islands",
    isoCode: "CK",
    threeLetterCode: "COK",
  ),
  CountryData(
    name: "Costa Rica",
    simplifiedName: "costa rica",
    isoCode: "CR",
    threeLetterCode: "CRI",
  ),
  CountryData(
    name: "Côte d'Ivoire",
    simplifiedName: "cote d'ivoire",
    isoCode: "CI",
    threeLetterCode: "CIV",
  ),
  CountryData(
    name: "Croatia",
    simplifiedName: "croatia",
    isoCode: "HR",
    threeLetterCode: "HRV",
  ),
  CountryData(
    name: "Cuba",
    simplifiedName: "cuba",
    isoCode: "CU",
    threeLetterCode: "CUB",
  ),
  CountryData(
    name: "Cyprus",
    simplifiedName: "cyprus",
    isoCode: "CY",
    threeLetterCode: "CYP",
  ),
  CountryData(
    name: "Djibouti",
    simplifiedName: "djibouti",
    isoCode: "DJ",
    threeLetterCode: "DJI",
  ),
  CountryData(
    name: "Dominica",
    simplifiedName: "dominica",
    isoCode: "DM",
    threeLetterCode: "DMA",
  ),
  CountryData(
    name: "Dominican Republic",
    simplifiedName: "dominican republic",
    isoCode: "DO",
    threeLetterCode: "DOM",
  ),
  CountryData(
    name: "Ecuador",
    simplifiedName: "ecuador",
    isoCode: "EC",
    threeLetterCode: "ECU",
  ),
  CountryData(
    name: "Egypt",
    simplifiedName: "egypt",
    isoCode: "EG",
    threeLetterCode: "EGY",
  ),
  CountryData(
    name: "El Salvador",
    simplifiedName: "el salvador",
    isoCode: "SV",
    threeLetterCode: "SLV",
  ),
  CountryData(
    name: "Equatorial Guinea",
    simplifiedName: "equatorial guinea",
    isoCode: "GQ",
    threeLetterCode: "GNQ",
  ),
  CountryData(
    name: "Eritrea",
    simplifiedName: "eritrea",
    isoCode: "ER",
    threeLetterCode: "ERI",
  ),
  CountryData(
    name: "Estonia",
    simplifiedName: "estonia",
    isoCode: "EE",
    threeLetterCode: "EST",
  ),
  CountryData(
    name: "Ethiopia",
    simplifiedName: "ethiopia",
    isoCode: "ET",
    threeLetterCode: "ETH",
  ),
  CountryData(
    name: "Falkland Islands (Malvinas)",
    simplifiedName: "falkland islands (malvinas)",
    isoCode: "FK",
    threeLetterCode: "FLK",
  ),
  CountryData(
    name: "Faroe Islands",
    simplifiedName: "faroe islands",
    isoCode: "FO",
    threeLetterCode: "FRO",
  ),
  CountryData(
    name: "Fiji",
    simplifiedName: "fiji",
    isoCode: "FJ",
    threeLetterCode: "FJI",
  ),
  CountryData(
    name: "French Guiana",
    simplifiedName: "french guiana",
    isoCode: "GF",
    threeLetterCode: "GUF",
  ),
  CountryData(
    name: "French Polynesia",
    simplifiedName: "french polynesia",
    isoCode: "PF",
    threeLetterCode: "PYF",
  ),
  CountryData(
    name: "French Southern Territories",
    simplifiedName: "french southern territories",
    isoCode: "TF",
    threeLetterCode: "ATF",
  ),
  CountryData(
    name: "Gabon",
    simplifiedName: "gabon",
    isoCode: "GA",
    threeLetterCode: "GAB",
  ),
  CountryData(
    name: "Gambia",
    simplifiedName: "gambia",
    isoCode: "GM",
    threeLetterCode: "GMB",
  ),
  CountryData(
    name: "Georgia",
    simplifiedName: "georgia",
    isoCode: "GE",
    threeLetterCode: "GEO",
  ),
  CountryData(
    name: "Ghana",
    simplifiedName: "ghana",
    isoCode: "GH",
    threeLetterCode: "GHA",
  ),
  CountryData(
    name: "Gibraltar",
    simplifiedName: "gibraltar",
    isoCode: "GI",
    threeLetterCode: "GIB",
  ),
  CountryData(
    name: "Greenland",
    simplifiedName: "greenland",
    isoCode: "GL",
    threeLetterCode: "GRL",
  ),
  CountryData(
    name: "Grenada",
    simplifiedName: "grenada",
    isoCode: "GD",
    threeLetterCode: "GRD",
  ),
  CountryData(
    name: "Guadeloupe",
    simplifiedName: "guadeloupe",
    isoCode: "GP",
    threeLetterCode: "GLP",
  ),
  CountryData(
    name: "Guam",
    simplifiedName: "guam",
    isoCode: "GU",
    threeLetterCode: "GUM",
  ),
  CountryData(
    name: "Guatemala",
    simplifiedName: "guatemala",
    isoCode: "GT",
    threeLetterCode: "GTM",
  ),
  CountryData(
    name: "Guernsey",
    simplifiedName: "guernsey",
    isoCode: "GG",
    threeLetterCode: "GGY",
  ),
  CountryData(
    name: "Guinea",
    simplifiedName: "guinea",
    isoCode: "GN",
    threeLetterCode: "GIN",
  ),
  CountryData(
    name: "Guinea-Bissau",
    simplifiedName: "guinea-bissau",
    isoCode: "GW",
    threeLetterCode: "GNB",
  ),
  CountryData(
    name: "Guyana",
    simplifiedName: "guyana",
    isoCode: "GY",
    threeLetterCode: "GUY",
  ),
  CountryData(
    name: "Haiti",
    simplifiedName: "haiti",
    isoCode: "HT",
    threeLetterCode: "HTI",
  ),
  CountryData(
    name: "Heard and Mcdonald Islands",
    simplifiedName: "heard and mcdonald islands",
    isoCode: "HM",
    threeLetterCode: "HMD",
  ),
  CountryData(
    name: "Holy See (Vatican City State)",
    simplifiedName: "holy see (vatican city state)",
    isoCode: "VA",
    threeLetterCode: "VAT",
  ),
  CountryData(
    name: "Honduras",
    simplifiedName: "honduras",
    isoCode: "HN",
    threeLetterCode: "HND",
  ),
  CountryData(
    name: "Hungary",
    simplifiedName: "hungary",
    isoCode: "HU",
    threeLetterCode: "HUN",
  ),
  CountryData(
    name: "India",
    simplifiedName: "india",
    isoCode: "IN",
    threeLetterCode: "IND",
  ),
  CountryData(
    name: "Indonesia",
    simplifiedName: "indonesia",
    isoCode: "ID",
    threeLetterCode: "IDN",
  ),
  CountryData(
    name: "Iran, Islamic Republic of",
    simplifiedName: "iran, islamic republic of",
    isoCode: "IR",
    threeLetterCode: "IRN",
  ),
  CountryData(
    name: "Iraq",
    simplifiedName: "iraq",
    isoCode: "IQ",
    threeLetterCode: "IRQ",
  ),
  CountryData(
    name: "Isle of Man",
    simplifiedName: "isle of man",
    isoCode: "IM",
    threeLetterCode: "IMN",
  ),
  CountryData(
    name: "Israel",
    simplifiedName: "israel",
    isoCode: "IL",
    threeLetterCode: "ISR",
  ),
  CountryData(
    name: "Jamaica",
    simplifiedName: "jamaica",
    isoCode: "JM",
    threeLetterCode: "JAM",
  ),
  CountryData(
    name: "Japan",
    simplifiedName: "japan",
    isoCode: "JP",
    threeLetterCode: "JPN",
  ),
  CountryData(
    name: "Jersey",
    simplifiedName: "jersey",
    isoCode: "JE",
    threeLetterCode: "JEY",
  ),
  CountryData(
    name: "Jordan",
    simplifiedName: "jordan",
    isoCode: "JO",
    threeLetterCode: "JOR",
  ),
  CountryData(
    name: "Kazakhstan",
    simplifiedName: "kazakhstan",
    isoCode: "KZ",
    threeLetterCode: "KAZ",
  ),
  CountryData(
    name: "Kenya",
    simplifiedName: "kenya",
    isoCode: "KE",
    threeLetterCode: "KEN",
  ),
  CountryData(
    name: "Kiribati",
    simplifiedName: "kiribati",
    isoCode: "KI",
    threeLetterCode: "KIR",
  ),
  CountryData(
    name: "Korea (North)",
    simplifiedName: "korea (north)",
    isoCode: "KP",
    threeLetterCode: "PRK",
  ),
  CountryData(
    name: "Korea (South)",
    simplifiedName: "korea (south)",
    isoCode: "KR",
    threeLetterCode: "KOR",
  ),
  CountryData(
    name: "Kuwait",
    simplifiedName: "kuwait",
    isoCode: "KW",
    threeLetterCode: "KWT",
  ),
  CountryData(
    name: "Kyrgyzstan",
    simplifiedName: "kyrgyzstan",
    isoCode: "KG",
    threeLetterCode: "KGZ",
  ),
  CountryData(
    name: "Lao PDR",
    simplifiedName: "lao pdr",
    isoCode: "LA",
    threeLetterCode: "LAO",
  ),
  CountryData(
    name: "Lebanon",
    simplifiedName: "lebanon",
    isoCode: "LB",
    threeLetterCode: "LBN",
  ),
  CountryData(
    name: "Lesotho",
    simplifiedName: "lesotho",
    isoCode: "LS",
    threeLetterCode: "LSO",
  ),
  CountryData(
    name: "Liberia",
    simplifiedName: "liberia",
    isoCode: "LR",
    threeLetterCode: "LBR",
  ),
  CountryData(
    name: "Libya",
    simplifiedName: "libya",
    isoCode: "LY",
    threeLetterCode: "LBY",
  ),
  CountryData(
    name: "Liechtenstein",
    simplifiedName: "liechtenstein",
    isoCode: "LI",
    threeLetterCode: "LIE",
  ),
  CountryData(
    name: "Lithuania",
    simplifiedName: "lithuania",
    isoCode: "LT",
    threeLetterCode: "LTU",
  ),
  CountryData(
    name: "Macedonia, Republic of",
    simplifiedName: "macedonia, republic of",
    isoCode: "MK",
    threeLetterCode: "MKD",
  ),
  CountryData(
    name: "Madagascar",
    simplifiedName: "madagascar",
    isoCode: "MG",
    threeLetterCode: "MDG",
  ),
  CountryData(
    name: "Malawi",
    simplifiedName: "malawi",
    isoCode: "MW",
    threeLetterCode: "MWI",
  ),
  CountryData(
    name: "Malaysia",
    simplifiedName: "malaysia",
    isoCode: "MY",
    threeLetterCode: "MYS",
  ),
  CountryData(
    name: "Maldives",
    simplifiedName: "maldives",
    isoCode: "MV",
    threeLetterCode: "MDV",
  ),
  CountryData(
    name: "Mali",
    simplifiedName: "mali",
    isoCode: "ML",
    threeLetterCode: "MLI",
  ),
  CountryData(
    name: "Marshall Islands",
    simplifiedName: "marshall islands",
    isoCode: "MH",
    threeLetterCode: "MHL",
  ),
  CountryData(
    name: "Martinique",
    simplifiedName: "martinique",
    isoCode: "MQ",
    threeLetterCode: "MTQ",
  ),
  CountryData(
    name: "Mauritania",
    simplifiedName: "mauritania",
    isoCode: "MR",
    threeLetterCode: "MRT",
  ),
  CountryData(
    name: "Mauritius",
    simplifiedName: "mauritius",
    isoCode: "MU",
    threeLetterCode: "MUS",
  ),
  CountryData(
    name: "Mayotte",
    simplifiedName: "mayotte",
    isoCode: "YT",
    threeLetterCode: "MYT",
  ),
  CountryData(
    name: "Mexico",
    simplifiedName: "mexico",
    isoCode: "MX",
    threeLetterCode: "MEX",
  ),
  CountryData(
    name: "Micronesia, Federated States of",
    simplifiedName: "micronesia, federated states of",
    isoCode: "FM",
    threeLetterCode: "FSM",
  ),
  CountryData(
    name: "Moldova",
    simplifiedName: "moldova",
    isoCode: "MD",
    threeLetterCode: "MDA",
  ),
  CountryData(
    name: "Monaco",
    simplifiedName: "monaco",
    isoCode: "MC",
    threeLetterCode: "MCO",
  ),
  CountryData(
    name: "Mongolia",
    simplifiedName: "mongolia",
    isoCode: "MN",
    threeLetterCode: "MNG",
  ),
  CountryData(
    name: "Montenegro",
    simplifiedName: "montenegro",
    isoCode: "ME",
    threeLetterCode: "MNE",
  ),
  CountryData(
    name: "Montserrat",
    simplifiedName: "montserrat",
    isoCode: "MS",
    threeLetterCode: "MSR",
  ),
  CountryData(
    name: "Morocco",
    simplifiedName: "morocco",
    isoCode: "MA",
    threeLetterCode: "MAR",
  ),
  CountryData(
    name: "Mozambique",
    simplifiedName: "mozambique",
    isoCode: "MZ",
    threeLetterCode: "MOZ",
  ),
  CountryData(
    name: "Myanmar",
    simplifiedName: "myanmar",
    isoCode: "MM",
    threeLetterCode: "MMR",
  ),
  CountryData(
    name: "Namibia",
    simplifiedName: "namibia",
    isoCode: "NA",
    threeLetterCode: "NAM",
  ),
  CountryData(
    name: "Nauru",
    simplifiedName: "nauru",
    isoCode: "NR",
    threeLetterCode: "NRU",
  ),
  CountryData(
    name: "Nepal",
    simplifiedName: "nepal",
    isoCode: "NP",
    threeLetterCode: "NPL",
  ),
  CountryData(
    name: "Netherlands Antilles",
    simplifiedName: "netherlands antilles",
    isoCode: "AN",
    threeLetterCode: "ANT",
  ),
  CountryData(
    name: "New Caledonia",
    simplifiedName: "new caledonia",
    isoCode: "NC",
    threeLetterCode: "NCL",
  ),
  CountryData(
    name: "New Zealand",
    simplifiedName: "new zealand",
    isoCode: "NZ",
    threeLetterCode: "NZL",
  ),
  CountryData(
    name: "Nicaragua",
    simplifiedName: "nicaragua",
    isoCode: "NI",
    threeLetterCode: "NIC",
  ),
  CountryData(
    name: "Niger",
    simplifiedName: "niger",
    isoCode: "NE",
    threeLetterCode: "NER",
  ),
  CountryData(
    name: "Nigeria",
    simplifiedName: "nigeria",
    isoCode: "NG",
    threeLetterCode: "NGA",
  ),
  CountryData(
    name: "Niue",
    simplifiedName: "niue",
    isoCode: "NU",
    threeLetterCode: "NIU",
  ),
  CountryData(
    name: "Norfolk Island",
    simplifiedName: "norfolk island",
    isoCode: "NF",
    threeLetterCode: "NFK",
  ),
  CountryData(
    name: "Northern Mariana Islands",
    simplifiedName: "northern mariana islands",
    isoCode: "MP",
    threeLetterCode: "MNP",
  ),
  CountryData(
    name: "Oman",
    simplifiedName: "oman",
    isoCode: "OM",
    threeLetterCode: "OMN",
  ),
  CountryData(
    name: "Pakistan",
    simplifiedName: "pakistan",
    isoCode: "PK",
    threeLetterCode: "PAK",
  ),
  CountryData(
    name: "Palau",
    simplifiedName: "palau",
    isoCode: "PW",
    threeLetterCode: "PLW",
  ),
  CountryData(
    name: "Palestinian Territory",
    simplifiedName: "palestinian territory",
    isoCode: "PS",
    threeLetterCode: "PSE",
  ),
  CountryData(
    name: "Panama",
    simplifiedName: "panama",
    isoCode: "PA",
    threeLetterCode: "PAN",
  ),
  CountryData(
    name: "Papua New Guinea",
    simplifiedName: "papua new guinea",
    isoCode: "PG",
    threeLetterCode: "PNG",
  ),
  CountryData(
    name: "Paraguay",
    simplifiedName: "paraguay",
    isoCode: "PY",
    threeLetterCode: "PRY",
  ),
  CountryData(
    name: "Peru",
    simplifiedName: "peru",
    isoCode: "PE",
    threeLetterCode: "PER",
  ),
  CountryData(
    name: "Philippines",
    simplifiedName: "philippines",
    isoCode: "PH",
    threeLetterCode: "PHL",
  ),
  CountryData(
    name: "Pitcairn",
    simplifiedName: "pitcairn",
    isoCode: "PN",
    threeLetterCode: "PCN",
  ),
  CountryData(
    name: "Puerto Rico",
    simplifiedName: "puerto rico",
    isoCode: "PR",
    threeLetterCode: "PRI",
  ),
  CountryData(
    name: "Qatar",
    simplifiedName: "qatar",
    isoCode: "QA",
    threeLetterCode: "QAT",
  ),
  CountryData(
    name: "Réunion",
    simplifiedName: "reunion",
    isoCode: "RE",
    threeLetterCode: "REU",
  ),
  CountryData(
    name: "Russian Federation",
    simplifiedName: "russian federation",
    isoCode: "RU",
    threeLetterCode: "RUS",
  ),
  CountryData(
    name: "Rwanda",
    simplifiedName: "rwanda",
    isoCode: "RW",
    threeLetterCode: "RWA",
  ),
  CountryData(
    name: "Saint-Barthélemy",
    simplifiedName: "saint-barthelemy",
    isoCode: "BL",
    threeLetterCode: "BLM",
  ),
  CountryData(
    name: "Saint Helena",
    simplifiedName: "saint helena",
    isoCode: "SH",
    threeLetterCode: "SHN",
  ),
  CountryData(
    name: "Saint Kitts and Nevis",
    simplifiedName: "saint kitts and nevis",
    isoCode: "KN",
    threeLetterCode: "KNA",
  ),
  CountryData(
    name: "Saint Lucia",
    simplifiedName: "saint lucia",
    isoCode: "LC",
    threeLetterCode: "LCA",
  ),
  CountryData(
    name: "Saint-Martin (French part)",
    simplifiedName: "saint-martin (french part)",
    isoCode: "MF",
    threeLetterCode: "MAF",
  ),
  CountryData(
    name: "Saint Pierre and Miquelon",
    simplifiedName: "saint pierre and miquelon",
    isoCode: "PM",
    threeLetterCode: "SPM",
  ),
  CountryData(
    name: "Saint Vincent and Grenadines",
    simplifiedName: "saint vincent and grenadines",
    isoCode: "VC",
    threeLetterCode: "VCT",
  ),
  CountryData(
    name: "Samoa",
    simplifiedName: "samoa",
    isoCode: "WS",
    threeLetterCode: "WSM",
  ),
  CountryData(
    name: "San Marino",
    simplifiedName: "san marino",
    isoCode: "SM",
    threeLetterCode: "SMR",
  ),
  CountryData(
    name: "Sao Tome and Principe",
    simplifiedName: "sao tome and principe",
    isoCode: "ST",
    threeLetterCode: "STP",
  ),
  CountryData(
    name: "Saudi Arabia",
    simplifiedName: "saudi arabia",
    isoCode: "SA",
    threeLetterCode: "SAU",
  ),
  CountryData(
    name: "Senegal",
    simplifiedName: "senegal",
    isoCode: "SN",
    threeLetterCode: "SEN",
  ),
  CountryData(
    name: "Serbia",
    simplifiedName: "serbia",
    isoCode: "RS",
    threeLetterCode: "SRB",
  ),
  CountryData(
    name: "Seychelles",
    simplifiedName: "seychelles",
    isoCode: "SC",
    threeLetterCode: "SYC",
  ),
  CountryData(
    name: "Sierra Leone",
    simplifiedName: "sierra leone",
    isoCode: "SL",
    threeLetterCode: "SLE",
  ),
  CountryData(
    name: "Singapore",
    simplifiedName: "singapore",
    isoCode: "SG",
    threeLetterCode: "SGP",
  ),
  CountryData(
    name: "Slovenia",
    simplifiedName: "slovenia",
    isoCode: "SI",
    threeLetterCode: "SVN",
  ),
  CountryData(
    name: "Solomon Islands",
    simplifiedName: "solomon islands",
    isoCode: "SB",
    threeLetterCode: "SLB",
  ),
  CountryData(
    name: "Somalia",
    simplifiedName: "somalia",
    isoCode: "SO",
    threeLetterCode: "SOM",
  ),
  CountryData(
    name: "South Africa",
    simplifiedName: "south africa",
    isoCode: "ZA",
    threeLetterCode: "ZAF",
  ),
  CountryData(
    name: "South Georgia and the South Sandwich Islands",
    simplifiedName: "south georgia and the south sandwich islands",
    isoCode: "GS",
    threeLetterCode: "SGS",
  ),
  CountryData(
    name: "South Sudan",
    simplifiedName: "south sudan",
    isoCode: "SS",
    threeLetterCode: "SSD",
  ),
  CountryData(
    name: "Sri Lanka",
    simplifiedName: "sri lanka",
    isoCode: "LK",
    threeLetterCode: "LKA",
  ),
  CountryData(
    name: "Sudan",
    simplifiedName: "sudan",
    isoCode: "SD",
    threeLetterCode: "SDN",
  ),
  CountryData(
    name: "Suri'name'",
    simplifiedName: "suri'name'",
    isoCode: "SR",
    threeLetterCode: "SUR",
  ),
  CountryData(
    name: "Svalbard and Jan Mayen Islands",
    simplifiedName: "svalbard and jan mayen islands",
    isoCode: "SJ",
    threeLetterCode: "SJM",
  ),
  CountryData(
    name: "Swaziland",
    simplifiedName: "swaziland",
    isoCode: "SZ",
    threeLetterCode: "SWZ",
  ),
  CountryData(
    name: "Syrian Arab Republic (Syria)",
    simplifiedName: "syrian arab republic (syria)",
    isoCode: "SY",
    threeLetterCode: "SYR",
  ),
  CountryData(
    name: "Taiwan, Republic of China",
    simplifiedName: "taiwan, republic of china",
    isoCode: "TW",
    threeLetterCode: "TWN",
  ),
  CountryData(
    name: "Tajikistan",
    simplifiedName: "tajikistan",
    isoCode: "TJ",
    threeLetterCode: "TJK",
  ),
  CountryData(
    name: "Tanzania, United Republic of",
    simplifiedName: "tanzania, united republic of",
    isoCode: "TZ",
    threeLetterCode: "TZA",
  ),
  CountryData(
    name: "Thailand",
    simplifiedName: "thailand",
    isoCode: "TH",
    threeLetterCode: "THA",
  ),
  CountryData(
    name: "Timor-Leste",
    simplifiedName: "timor-leste",
    isoCode: "TL",
    threeLetterCode: "TLS",
  ),
  CountryData(
    name: "Togo",
    simplifiedName: "togo",
    isoCode: "TG",
    threeLetterCode: "TGO",
  ),
  CountryData(
    name: "Tokelau",
    simplifiedName: "tokelau",
    isoCode: "TK",
    threeLetterCode: "TKL",
  ),
  CountryData(
    name: "Tonga",
    simplifiedName: "tonga",
    isoCode: "TO",
    threeLetterCode: "TON",
  ),
  CountryData(
    name: "Trinidad and Tobago",
    simplifiedName: "trinidad and tobago",
    isoCode: "TT",
    threeLetterCode: "TTO",
  ),
  CountryData(
    name: "Tunisia",
    simplifiedName: "tunisia",
    isoCode: "TN",
    threeLetterCode: "TUN",
  ),
  CountryData(
    name: "Turkey",
    simplifiedName: "turkey",
    isoCode: "TR",
    threeLetterCode: "TUR",
  ),
  CountryData(
    name: "Turkmenistan",
    simplifiedName: "turkmenistan",
    isoCode: "TM",
    threeLetterCode: "TKM",
  ),
  CountryData(
    name: "Turks and Caicos Islands",
    simplifiedName: "turks and caicos islands",
    isoCode: "TC",
    threeLetterCode: "TCA",
  ),
  CountryData(
    name: "Tuvalu",
    simplifiedName: "tuvalu",
    isoCode: "TV",
    threeLetterCode: "TUV",
  ),
  CountryData(
    name: "Uganda",
    simplifiedName: "uganda",
    isoCode: "UG",
    threeLetterCode: "UGA",
  ),
  CountryData(
    name: "Ukraine",
    simplifiedName: "ukraine",
    isoCode: "UA",
    threeLetterCode: "UKR",
  ),
  CountryData(
    name: "United Arab Emirates",
    simplifiedName: "united arab emirates",
    isoCode: "AE",
    threeLetterCode: "ARE",
  ),
  CountryData(
    name: "US Minor Outlying Islands",
    simplifiedName: "us minor outlying islands",
    isoCode: "UM",
    threeLetterCode: "UMI",
  ),
  CountryData(
    name: "Uruguay",
    simplifiedName: "uruguay",
    isoCode: "UY",
    threeLetterCode: "URY",
  ),
  CountryData(
    name: "Uzbekistan",
    simplifiedName: "uzbekistan",
    isoCode: "UZ",
    threeLetterCode: "UZB",
  ),
  CountryData(
    name: "Vanuatu",
    simplifiedName: "vanuatu",
    isoCode: "VU",
    threeLetterCode: "VUT",
  ),
  CountryData(
    name: "Venezuela (Bolivarian Republic)",
    simplifiedName: "venezuela (bolivarian republic)",
    isoCode: "VE",
    threeLetterCode: "VEN",
  ),
  CountryData(
    name: "Virgin Islands, US",
    simplifiedName: "virgin islands, us",
    isoCode: "VI",
    threeLetterCode: "VIR",
  ),
  CountryData(
    name: "Wallis and Futuna Islands",
    simplifiedName: "wallis and futuna islands",
    isoCode: "WF",
    threeLetterCode: "WLF",
  ),
  CountryData(
    name: "Western Sahara",
    simplifiedName: "western sahara",
    isoCode: "EH",
    threeLetterCode: "ESH",
  ),
  CountryData(
    name: "Yemen",
    simplifiedName: "yemen",
    isoCode: "YE",
    threeLetterCode: "YEM",
  ),
  CountryData(
    name: "Zambia",
    simplifiedName: "zambia",
    isoCode: "ZM",
    threeLetterCode: "ZMB",
  ),
  CountryData(
    name: "Zimbabwe",
    simplifiedName: "zimbabwe",
    isoCode: "ZW",
    threeLetterCode: "ZWE",
  ),
];
