import 'package:flutter/material.dart';
import 'package:lite_forms/base_form_fields/lite_form_group.dart';
import 'package:lite_forms/controllers/lite_form_controller.dart';
import 'package:lite_forms/utils/string_extensions.dart';
import 'package:lite_forms/utils/value_serializer.dart';
import 'package:lite_forms/utils/value_validator.dart';

typedef OnChanged = Function(Object? value);

mixin FormFieldMixin<T extends StatefulWidget> on State<T> {
  LiteFormGroup? _group;
  LiteFormGroup get group => _group!;

  late final FormGroupField field;
  late final String _fieldName;

  dynamic _initialValue;
  dynamic get initialValue {
    return _initialValue;
  }

  String? hintText;
  TextStyle? _errorStyle;

  String get formName => group.name;

  InputDecoration? _decoration;
  InputDecoration get decoration => _decoration!;
  bool _isInitialized = false;

  TextEditingController? get textEditingController {
    return field.getOrCreateTextEditingController();
  }

  /// Checks if a field is initially set to not let it
  /// set initially again
  bool setInitialValue({
    required String formName,
    required String fieldName,
    required VoidCallback setter,
  }) {
    if (!liteFormController.isFieldInitiallySet(
      formName: formName,
      fieldName: fieldName,
    )) {
      setter();
      return true;
    }
    return false;
  }

  void tryDeserializeInitialValueIfNecessary<E>({
    required Object? rawInitialValue,
    required LiteFormValueSerializer? initialValueDeserializer,
  }) {
    final storedValue = liteFormController.tryGetValueForField(
      formName: group.name,
      fieldName: _fieldName,
    ) as E?;
    if (E == String) {
      _initialValue = storedValue ??
          initialValueDeserializer?.call(rawInitialValue)?.toString() ??
          rawInitialValue?.toString();
    } else {
      _initialValue = storedValue ??
          initialValueDeserializer?.call(rawInitialValue) as E? ??
          rawInitialValue as E?;
    }
  }

  void initializeFormField<E>({
    required String fieldName,
    required AutovalidateMode? autovalidateMode,
    required LiteFormValueSerializer serializer,
    required LiteFormValueSerializer? initialValueDeserializer,
    required List<LiteFormFieldValidator<Object?>>? validators,
    required String? hintText,
    required InputDecoration? decoration,
    required TextStyle? errorStyle,
  }) {
    _group = LiteFormGroup.of(context)!;
    this._decoration = decoration ??
        formConfig?.inputDecoration ??
        const InputDecoration();
    this.hintText = group.translationBuilder(hintText);
    if (hintText?.isNotEmpty != true) {
      if (formConfig?.useAutogeneratedHints == true) {
        this.hintText = fieldName.splitByCamelCase();
      }
    }
    if (this.hintText?.isNotEmpty == true) {
      this._decoration = this._decoration?.copyWith(
            hintText: this.hintText,
          );
    }

    if (!_isInitialized) {
      _isInitialized = true;
      _errorStyle = errorStyle;
      _fieldName = fieldName;
      field = liteFormController.registerFormFieldIfNone<E>(
        fieldName: _fieldName,
        formName: group.name,
        serializer: serializer,
        validators: validators,
        decoration: decoration,
        autovalidateMode: autovalidateMode,
      );
    }
  }

  TextStyle get errorStyle {
    return _errorStyle ??
        formConfig?.inputDecoration?.errorStyle ??
        TextStyle(color: Theme.of(context).colorScheme.error);
  }
}
