// ignore_for_file: depend_on_referenced_packages

import 'package:flutter/material.dart';
import 'package:lite_forms/base_form_fields/exports.dart';
import 'package:lite_forms/intl_local/lib/intl.dart';
import 'package:lite_forms/utils/controller_initializer.dart';

import 'start_page.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    const defaultBorder = OutlineInputBorder(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular(
          30.0,
        ),
        topRight: Radius.circular(
          10.0,
        ),
        bottomRight: Radius.circular(
          30.0,
        ),
        bottomLeft: Radius.circular(
          10.0,
        ),
      ),
    );

    /// Must be called in the beginning.
    /// Basically that's all you need
    /// to start using Lite Forms
    initializeLiteForms(
      /// optional configuration which will be used as default
      config: LiteFormsConfiguration(
        defaultDatePickerFormat: DateFormat('dd MMMM, yyyy'),
        autovalidateMode: AutovalidateMode.onUserInteraction,
        useAutogeneratedHints: true,
        allowUnfocusOnTapOutside: true,
        defaultTextEntryModalRouteSettings: TextEntryModalRouteSettings(
          backgroundOpacity: .95,
        ),
        inputDecoration: InputDecoration(
            filled: false,
            errorStyle: const TextStyle(
              fontSize: 16.0,
              color: Colors.orange,
            ),
            border: defaultBorder,
            enabledBorder: defaultBorder.copyWith(
              borderSide: const BorderSide(
                width: .1,
              ),
            ),
            focusedBorder: defaultBorder.copyWith(
              borderSide: const BorderSide(
                width: 3,
                color: Colors.blue,
              ),
            )),
      ),
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Lite Forms Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const StartPage(),
    );
  }
}
