import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:lite_forms/controllers/lite_form_controller.dart';
import 'package:lite_state/lite_state.dart';

/// Call it somewhere in the beginning of your app code
/// [config] allows you to configure the look and feel
/// for all of your form fields by default.
/// Doing this you won't have to set decorations, paddings
/// and other common stuff for your forms everywhere
void initializeLiteForms({
  LiteFormsConfiguration? config,
}) {
  initControllersLazy({
    LiteFormController: () => LiteFormController(),
  });
  if (config != null) {
    liteFormController.configureLiteFormUI(
      config: config,
    );
  }
}

class LiteFormsConfiguration {
  final InputDecoration? inputDecoration;
  final AutovalidateMode? autovalidateMode;
  final DateFormat? defaultPickerFormat;
  /// if this is true and you don't pass hintText to a 
  /// form field, it will automatically generate it based on the field's name 
  /// value, using splitByCamelCase method()
  final bool useAutogeneratedHints;

  LiteFormsConfiguration({
    this.inputDecoration,
    this.autovalidateMode,
    this.defaultPickerFormat,
    this.useAutogeneratedHints = false,
  });
}
